[package]
name = "enum_router"
version = "0.1.0"
edition = "2021"


[workspace]
members = [
  "enum_router_macro"
]

[dependencies]
enum_router_macro = { path = "enum_router_macro", version = "0.1.0" }

